### ISSUE TITLE
Can't load config on fresh build

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/bengoshi-js#2]
```

/home/.../Projects/bengoshi-js/src/asset-server.js:10
const config = require('./config').config.asset_server;
                                         ^

TypeError: Cannot read property 'asset_server' of undefined
    at Object.<anonymous> (/home/.../Projects/bengoshi-js/src/asset-server.js:10:42)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/.../Projects/bengoshi-js/index.js:9:24)
    at Module._compile (module.js:649:30)
```
The default config is not being captured.

**Comment by nnoodle** [comment]
Fixed in the refactor branch
https://github.com/AttorneyOnline/bengoshi-js/blob/63e756735e0a8f92310883476eade213453f1699/src/asset-server.js#L10
